import {test,expect,config} from '../fixtures/baseTest'; import {VisitBookingPage} from '../pages/VisitBookingPage';
test.describe('CMO normal cases',()=>{test.beforeEach(async({page,loginPage})=>{await page.goto(config.url);await loginPage.login(config.username,config.password);await expect(page).toHaveURL(/clinicaldiary|user/);});
test('login with valid credentials',async({page})=>{await expect(page).toHaveURL(/clinicaldiary|user/);});
test('visit booking',async({page})=>{await page.goto(config.visitBookingUrl);const p=new VisitBookingPage(page);await p.selectClinic();await p.selectPractitioner();});
test('cancel visit',async({page})=>{await page.goto(config.visitBookingUrl);await new VisitBookingPage(page).CancelBookedVisit();});
test('cancel appointment',async({page})=>{await page.goto(config.visitBookingUrl);await new VisitBookingPage(page).CancelAppointment();});
test('change language',async({page})=>{await page.goto(config.visitBookingUrl);await new VisitBookingPage(page).switchToArabicLanguage();});
test('search patient by ID',async({page})=>{await page.goto(config.visitBookingUrl);await new VisitBookingPage(page).SearchPatientID('B600007148');});
test('search patient by name',async({page})=>{await page.goto(config.visitBookingUrl);await new VisitBookingPage(page).SearchPatientName('test');});
test('search patient by national ID',async({page})=>{await page.goto(config.visitBookingUrl);await new VisitBookingPage(page).SearchNationalID('43213431234234');});
test('search patient by gender',async({page})=>{await page.goto(config.visitBookingUrl);await new VisitBookingPage(page).SearchPatientGenderMale('test');});
test('search patient by female gender',async({page})=>{await page.goto(config.visitBookingUrl);await new VisitBookingPage(page).SearchPatientGenderFemale('test');});
test('print bill',async({page})=>{await page.goto(config.visitBookingUrl);await new VisitBookingPage(page).BillPage('test');});
test('pay bill',async({page})=>{await page.goto(config.visitBookingUrl);await new VisitBookingPage(page).PayBill('test');});});